### ISSUE TITLE
Start in docker fails

### ISSUE THREAD

**Issue by rcemper** [alexnxela/iris-recorder-helper#1]
irisowner@2bbb2b066320:~/dev$ irispython ./rh/flask/main.py
**/home/irisowner/dev/rh/flask/app/config.b64 not found**

this is referred in config.py
````
# Default config variables
import json
import os
import sys
import base64

APP_PATH = os.path.dirname(os.path.abspath(__file__))
JSON_CONFIG_PATH = APP_PATH+"/config.b64"
.....
````

**Comment by alexnxela** [comment]
Hi @rcemper 
Thank you very much for the feedback, but I made a mistake when setting up the deploy

I fix it, now the local environment is launched on config.json file (https://github.com/alexnxela/iris-recorder-helper/commit/006d40edf10576544ecc7ee8b8b1a096ff30550f) 

If there were difficulties in obtaining an openai key, you can get it from the link https://platform.openai.com/account/api-keys
Or more details in the video https://www.youtube.com/watch?v=EQQjdwdVQ-M

**Comment by rcemper** [comment]
the startup works nowBUT your README says

You should put the parameters file here **./rh/flask/config.json**
>>>
irisowner@2dc78d41d315:~/dev$ irispython ./rh/flask/main.py
/home/irisowner/dev/**rh/flask/app/config.json** not found
>>>
I moved it to **rh/flask/app/config.json**  and it workked

**Comment by rcemper** [comment]
my experience:
- make sure your phone is operational
- use a fresh API key
- use an anonymous browser session
- speak English or American 

Rating OEX review raised to 4.5 !
